version: '3.8'
services:
  # 1. 로컬 DynamoDB (가짜 AWS DB)
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./data:/home/dynamodblocal/data" # 데이터 영구 저장 (껐다 켜도 유지)
    working_dir: /home/dynamodblocal

  # 2. DynamoDB Admin (GUI 툴 - http://localhost:8001)
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "ap-northeast-2"
      AWS_ACCESS_KEY_ID: "local"
      AWS_SECRET_ACCESS_KEY: "local"
    depends_on:
      - dynamodb-local